
// Stores the sequence generated by the game
let gameSeq = [];

// Stores the sequence entered by the user
let usserSeq = [];

// Available button colors
let btns = ["yellow", "red", "purple", "green"];

// Tracks whether the game has started
let started = false;

// Current level
let level = 0;

// Heading used to display level and game status
let h2 = document.querySelector("h2");

// Start game when any key is pressed
document.addEventListener("keypress", function () {
    if (started == false) {
        console.log("started");
        started = true;
    }

    levelUp();
});

// Flash effect for game-generated button
function gameFlash(btn) {
    btn.classList.add("flash");

    setTimeout(function () {
        btn.classList.remove("flash");
    }, 100);
}

// Flash effect for user click
function userFlash(btn) {
    btn.classList.add("userFlash");

    setTimeout(function () {
        btn.classList.remove("userFlash");
    }, 100);
}

// Move game to the next level
function levelUp() {

    // Reset user sequence for new level
    usserSeq = [];

    level++;
    h2.innerText = `Level ${level}`;

    // Generate random color button
    let randomIdx = Math.floor(Math.random() * btns.length);
    let randomColor = btns[randomIdx];

    let randomBtn = document.querySelector(`.${randomColor}`);

    // Add color to game sequence
    gameSeq.push(randomColor);

    console.log(gameSeq);

    // Flash selected button
    gameFlash(randomBtn);
}

// Check user's answer
function checkAns(idx) {

    if (usserSeq[idx] == gameSeq[idx]) {

        // Move to next level when sequence is completed
        if (usserSeq.length == gameSeq.length) {
            setTimeout(levelUp, 1000);
        }

    } else {

        // Game Over
        h2.innerHTML =
            `Game Over! Your Score was <b>${level}</b> <br>Press any key to restart`;

        document.querySelector("body").style.backgroundColor = "red";

        setTimeout(function () {
            document.querySelector("body").style.backgroundColor = "#f5f5f5";
        }, 150);

        reset();
    }
}

// Handle user button click
function btnPress() {

    let btn = this;

    userFlash(btn);

    usserColor = btn.getAttribute("id");

    console.log(usserColor);

    usserSeq.push(usserColor);

    checkAns(usserSeq.length - 1);
}

// Add click event to all buttons
let allBtns = document.querySelectorAll(".btn");

for (b of allBtns) {
    b.addEventListener("click", btnPress);
}

// Reset game variables
function reset() {
    started = false;
    gameSeq = [];
    usserSeq = [];
    level = 0;
}

